## Task 3


In [49]:
#Create an empty and a full NumPy array

In [50]:
import numpy as np

In [51]:
empty_arr = np.empty((3,3,3))
print(empty_arr)

[[[2.7e-322 2.7e-322 2.7e-322]
  [2.7e-322 2.7e-322 2.7e-322]
  [2.7e-322 2.7e-322 2.7e-322]]

 [[2.7e-322 2.7e-322 2.7e-322]
  [2.7e-322 2.7e-322 2.7e-322]
  [2.7e-322 2.7e-322 2.7e-322]]

 [[2.7e-322 2.7e-322 2.7e-322]
  [2.7e-322 2.7e-322 2.7e-322]
  [2.7e-322 2.7e-322 2.7e-322]]]


In [52]:
full_arr = np.full((3,3,3),24)
print(full_arr)

[[[24 24 24]
  [24 24 24]
  [24 24 24]]

 [[24 24 24]
  [24 24 24]
  [24 24 24]]

 [[24 24 24]
  [24 24 24]
  [24 24 24]]]


In [53]:
#Create a Numpy array filled with all zeros

In [54]:
arr_0 = np.zeros((3,4,3))
print(arr_0)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [55]:
#Create a Numpy array filled with all ones

In [56]:
arr_1 = np.ones((4,3,4))
print(arr_1)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [57]:
# Replace NumPy array elements that don’t satisfy a given condition


In [64]:
array = np.random.randint(50, size=(4,4,4))
print(array)

[[[46  2 37 33]
  [16 28 38 35]
  [20 35 39 36]
  [ 8 13  7 38]]

 [[ 6 33 43 26]
  [39 42 29  5]
  [42 35  7 24]
  [ 6  3 26 22]]

 [[26  9 18  9]
  [44 17 27 19]
  [ 4 36 17 26]
  [ 4 44 10 35]]

 [[48  6 17 49]
  [ 6 11 41  5]
  [29 23 42 29]
  [49  3  1 10]]]


In [59]:
array.shape

(4, 4, 4)

In [65]:
#cheking if the element of the array are even or not, if odd then the value changed to zero

In [66]:
print("Array before checking the condition\n")
print(array)

for i in range(4):
  for j in range(4):
    for k in range(4):
      if array[i,j,k]%2 == 0:
        pass
      else:
        array[i,j,k] = 0

print("\nArray after checking the condition and replacing the values\n")
print(array)




Array before checking the condition

[[[46  2 37 33]
  [16 28 38 35]
  [20 35 39 36]
  [ 8 13  7 38]]

 [[ 6 33 43 26]
  [39 42 29  5]
  [42 35  7 24]
  [ 6  3 26 22]]

 [[26  9 18  9]
  [44 17 27 19]
  [ 4 36 17 26]
  [ 4 44 10 35]]

 [[48  6 17 49]
  [ 6 11 41  5]
  [29 23 42 29]
  [49  3  1 10]]]

Array after checking the condition and replacing the values

[[[46  2  0  0]
  [16 28 38  0]
  [20  0  0 36]
  [ 8  0  0 38]]

 [[ 6  0  0 26]
  [ 0 42  0  0]
  [42  0  0 24]
  [ 6  0 26 22]]

 [[26  0 18  0]
  [44  0  0  0]
  [ 4 36  0 26]
  [ 4 44 10  0]]

 [[48  6  0  0]
  [ 6  0  0  0]
  [ 0  0 42  0]
  [ 0  0  0 10]]]


In [ ]:
#Get the maximum value from a matrix


In [68]:
array = np.random.randint(50, size=(4,4,4))
print(array)
print(f"\nThe maximum value of the matrix is: {array.max()} ")

[[[27 11  2 38]
  [48 15 22 10]
  [16 13  0 16]
  [42 32 45  0]]

 [[42 21 15  8]
  [26 47 30  6]
  [43 23 10  8]
  [24  3 16 19]]

 [[ 8 25  6  3]
  [ 9 19  5 39]
  [23 18 28 13]
  [26  9 43 47]]

 [[42 45 20 18]
  [42 15 39 32]
  [18 19 48 29]
  [42 35 43 28]]]

The maximum value of the matrix is: 48 
